In [8]:
import numpy as np
from scipy.sparse import csc_array
import pickle

In [9]:
with open('amogi_by_time (1).pickle', 'rb') as handle:
    b = pickle.load(handle)

In [15]:
b[1648822500][0]

array([ 10,  10,  13,  23,  40,  57,  75,  93, 103, 111, 112, 114, 115,
       121, 122, 130, 145, 163, 165, 245, 257, 269, 269, 276, 279, 282,
       284, 296, 304, 325, 326, 330, 334, 336, 338, 346, 349, 350, 361,
       369, 373, 375, 379, 381, 387, 388, 393, 397, 398, 403, 404, 406,
       406, 406, 417, 421, 431, 444, 446, 463, 463, 466, 477, 481, 485,
       493, 498, 499, 500, 501, 507, 510, 515, 517, 525, 525, 528, 530,
       535, 536, 538, 539, 540, 544, 545, 547, 550, 561, 566, 567, 573,
       580, 587, 592, 605, 614, 622, 628, 630, 633, 644, 664, 672, 696,
       707, 720, 727, 727, 730, 732, 732, 743, 744, 745, 752, 755, 759,
       761, 763, 766, 774, 775, 781, 786, 790, 796, 796, 800, 803, 814,
       867, 879, 885, 886, 894, 895, 919, 926, 928, 930, 943, 944, 952,
       961, 967, 969, 970, 972, 972, 972, 973, 977, 977, 977, 977, 977,
       977, 977, 977, 977, 977, 977, 977, 977, 977, 977, 977, 977, 977,
       977, 977, 977, 977, 977, 977, 977, 977, 977, 977, 977, 97

In [18]:
heatmap = np.zeros(shape = (2000,2000))
for key in b.keys():
    x = b[key][0]
    y = b[key][1]
    val = b[key][2]
    data = np.ones((len(x)),dtype='uint8')
    layer = csc_array((data, (x, y)),shape = (2000,2000)).toarray()
    print(len(layer.nonzero()[0]))
    heatmap =+ layer 
    break

350


In [12]:
x,y = heatmap.nonzero()
x.shape

(0,)

In [11]:
key = 1648822500
x = b[key][0]
y = b[key][1]
val = b[key][2]

data = np.ones((len(x)),dtype='uint8')

In [17]:
heatmap = csc_array((data, (x, y)),shape = (2000,2000)).toarray()
heatmap.shape

(2000, 2000)

In [ ]:
csc_array((3, 4), dtype=np.int8).toarray()
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)



    
    
    
row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
csc_array((data, (row, col)), shape=(3, 3)).toarray()
array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]])